# Docker Compose Override for Development
# This file is automatically loaded with docker-compose.yml in development
# Use: docker compose up (automatically includes override)

services:
  # Development overrides for backend
  backend:
    build:
      target: base  # Use base stage for development
    environment:
      - FLASK_ENV=development
      - DEBUG=true
    volumes:
      # Mount source code for hot reload
      - ./backend:/app:delegated
      - backend_node_modules:/app/node_modules
    command: python main.py
    stdin_open: true
    tty: true

  # Development overrides for frontend  
  frontend:
    build:
      target: deps  # Use deps stage for development
    environment:
      - NODE_ENV=development
    volumes:
      # Mount source code for hot reload
      - ./frontend:/app:delegated
      - frontend_node_modules:/app/node_modules
      - /app/.next
    command: npm run dev
    stdin_open: true
    tty: true

volumes:
  backend_node_modules:
  frontend_node_modules: