"""Add consumption model

Revision ID: 483a1c3bdaaf
Revises: 0ed55baa0765
Create Date: 2025-10-31 15:09:25.427381

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '483a1c3bdaaf'
down_revision = '0ed55baa0765'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('consumptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('value', sa.Numeric(precision=10, scale=2), nullable=False, comment='Consumption value with 2 decimal places'),
    sa.Column('type', sa.String(length=20), nullable=False, comment='Type of consumption: electricity, water, or gas'),
    sa.Column('notes', sa.Text(), nullable=True, comment='Optional notes about the consumption record'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('consumptions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_consumptions_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('consumptions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_consumptions_user_id'))

    op.drop_table('consumptions')
    # ### end Alembic commands ###
